name: github-pipeline
on:
  workflow_dispatch:
jobs:
  Generate_Start_Timestamp:
    name: Generate Start Timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=starttimestamp::$("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")"
      - name: Store date as environment variable
        env:
          STARTTIMESTAMP: ${{ steps.date.outputs.starttimestamp }}
        run: echo "Start timestamp :" ${ env.starttimestamp } and ${currentBuild.number}   
    
