name: github-pipeline
on:
  push: 
   branches: [master]

env:
  BACKEND_REPO: 'Gitanshu3/assignment'
  BACKEND_BRANCH: 'master'
  INSTALLER_REPO: 'SmartBear/zephyr-standalone-installer'
  INSTALLER_BRANCH: 'branch_8.0'
  
jobs:
  
  Git_Pulls:
      name: Git Pulls Backend repository
      runs-on: ubuntu-latest
      
      steps:
      - name: Get StartTimestamp
        id: current_date
        run: echo "STARTTIMESTAMP=$(current_date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUPUT
        
      - name: Print StartTimestamp
        run: echo ${{ steps.current_date.STARTTIMESTAMP }} and ${{github.run_number}}
        
      - name: Checkout BackEnd Code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_BRANCH }}
          fetch-depth: 0
          # path: Integration/branch_integration/

      - name: Checkout Installer Code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_BRANCH }}
          fetch-depth: 0
          path: installer/

      - name: Checkout FrontEnd Code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_BRANCH }}
          fetch-depth: 0
          path: fayre/
          
      - name: Print mvn path
        run: |
          echo $PATH
          mvn -version
          ant -version

      - name: run ant build
        run: |
         echo " catalina base is ${CATALINA_BASE} "
         echo " workspace is ${GITHUB_WORKSPACE} "
         echo " This repo is ${{ github.repository }} .. "
         ant all -Dyourchoice=4 -DbambooBuildNumber=${{github.run_number}} -DMOBILE_BUILD_SKIP=true -v -verbose
        working-directory: .
         
            
      - name: Generate Build Number
        id: buildNumber
        shell: bash
        run: echo "##[set-output name=gitBuildnumber;]$(git rev-list HEAD | wc -l)"
        
      - name: Generate ZEBuildNumber
        id: zebuildnumber
        shell: bash
        run: |
         echo "##[set-output name=gitSha;]$(git rev-parse origin/${{ env.BACKEND_BRANCH }})"
         echo "zeBuildnumber=$(echo ${{ env.INSTALLER_BRANCH }} | cut -d'_' -f2)_${{ steps.buildNumber.outputs.gitBuildnumber }}" >> $GITHUB_OUTPUT
      
      - name: Print ZEBuildNumber
        shell: bash
        run: |
         ls -d -- */
         echo ZEBuildNumber- ${{ steps.zebuildnumber.outputs.zeBuildnumber }}
         echo gitSha - ${{steps.zebuildnumber.outputs.gitSha}}


  # Run_ANT_Build:
  #     name: Run ANT Build
  #     runs-on: ubuntu-latest
  #     needs: Git_Pulls
  #     steps:
  #       - name: Set up JDK 17
  #         uses: actions/setup-java@v2
  #         with:
  #           java-version: 17
  #           distribution: 'temurin'
    
  #       - name: run ant build
  #         run: |
  #          echo " catalina base is ${CATALINA_BASE} "
  #          echo " workspace is ${GITHUB_WORKSPACE} "
  #          echo " This repo is ${{ github.repository }} .. "
  #          ant all -Dyourchoice=4 -DbambooBuildNumber=${{github.run_number}} -DMOBILE_BUILD_SKIP=true -v -verbose 
  #         working-directory: Integration/branch_integration
  
