name: github-pipeline
on:
  workflow_dispatch:
jobs:
  Generate_Start_Timestamp:
    name: Generate Start Timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "STARTTIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Store date as environment variable
        run: echo "Start timestamp :" ${ env.starttimestamp } and ${{github.run_number}}
        env:
          STARTTIMESTAMP: ${{ steps.date.outputs.starttimestamp }}
    
