name: github-pipeline
on:
  push: 
   branches: [master]

env:
  BACKEND_REPO: 'Gitanshu3/assignment'
  BACKEND_BRANCH: 'master'
  INSTALLER_REPO: 'SmartBear/zephyr-standalone-installer'
  INSTALLER_BRANCH: 'branch_8.0'
  
jobs:
  Generate_Start_Timestamp:
    name: Generate Start Timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "STARTTIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $STARTTIMESTAMP and ${{github.run_number}}

  
  Git_Pulls:
      name: Git Pulls Backend repository
      runs-on: ubuntu-latest
      needs: Generate_Start_Timestamp
      steps:
      - name: Checkout BackEnd Code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_BRANCH }}
          fetch-depth: 0
          path: Integration/branch_integration/
          
      - name: Print Directory
        run: echo "github workplace one ${GITHUB_WORKSPACE}" 

      - name: Checkout Installer Code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_BRANCH }}
          fetch-depth: 0
          path: Integration/branch_integration/installer
      - name: Print Directory     
        run: echo "github workplace two ${GITHUB_WORKSPACE}" 

      - name: Checkout FrontEnd Code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_BRANCH }}
          fetch-depth: 0
          path: Integration/branch_integration/fayre'
      - name: Print Directory   
        shell: bash
        run: |
         echo "github workplace three ${GITHUB_WORKSPACE}" 
         echo "pwd is ${pwd}"
         cp -r "/usr/share/ant/lib" "${GITHUB_WORKSPACE}/Integration/branch_integration/"

      - name: run ant build
        run: |
         echo " catalina base is ${CATALINA_BASE} "
         echo " workspace is ${GITHUB_WORKSPACE} "
         echo " This repo is ${{ github.repository }} .. "
         ant all -Dyourchoice=4 -DbambooBuildNumber=${{github.run_number}} -DMOBILE_BUILD_SKIP=true -v -verbose
        working-directory: Integration/branch_integration 
         
            
      - name: Generate Build Number
        id: buildNumber
        shell: bash
        run: echo "##[set-output name=gitBuildnumber;]$(git rev-list HEAD | wc -l)"
        
      - name: Generate ZEBuildNumber
        id: zebuildnumber
        shell: bash
        run: |
         echo "zeBuildnumber=$(echo ${{ env.INSTALLER_BRANCH }} | cut -d'_' -f2)_${{ steps.buildNumber.outputs.gitBuildnumber }}" >> $GITHUB_OUTPUT
      
      - name: Print ZEBuildNumber
        shell: bash
        run: |
         ls -d -- */
         echo ZEBuildNumber- ${{ steps.zebuildnumber.outputs.zeBuildnumber }}


  # Run_ANT_Build:
  #     name: Run ANT Build
  #     runs-on: ubuntu-latest
  #     needs: Git_Pulls
  #     steps:
  #       - name: Set up JDK 17
  #         uses: actions/setup-java@v2
  #         with:
  #           java-version: 17
  #           distribution: 'temurin'
    
  #       - name: run ant build
  #         run: |
  #          echo " catalina base is ${CATALINA_BASE} "
  #          echo " workspace is ${GITHUB_WORKSPACE} "
  #          echo " This repo is ${{ github.repository }} .. "
  #          ant all -Dyourchoice=4 -DbambooBuildNumber=${{github.run_number}} -DMOBILE_BUILD_SKIP=true -v -verbose 
  #         working-directory: Integration/branch_integration
  
