name: github-pipeline
on:
  workflow_dispatch:

env:
  BACKEND_REPO: 'Gitanshu3/assignment'
  BACKEND_BRANCH: 'master'
  INSTALLER_REPO: 'SmartBear/zephyr-standalone-installer'
  INSTALLER_BRANCH: 'branch_8.0'
  
jobs:
  Generate_Start_Timestamp:
    name: Generate Start Timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "STARTTIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $STARTTIMESTAMP and ${{github.run_number}}

  
  Git_Pulls:
      name: Git Pulls Backend repository
      runs-on: ubuntu-latest
      needs: Generate_Start_Timestamp
      steps:
        - name: Checkout BackEnd Code
          uses: actions/checkout@v2
          with:
            repository: ${{ env.BACKEND_REPO }}
            ref: ${{ env.BACKEND_BRANCH }}
            fetch-depth: 0
        - name: Generate Build Number
          id: buildNumber
          shell: bash
          run: echo "##[set-output name=gitBuildnumber;]$(git rev-list HEAD | wc -l)"
          
        - name: Print ZEBuildNumber
          run: echo ${{ steps.ZEBuildNumber.outputs.ZEBuildNumber }}
          
        - name: Generate ZEBuildNumber
          id: ZEBuildNumber
          shell: bash
          run: echo "##[set-ouput name=ZEBuildNumber;]$(echo ${{ env.INSTALLER_BRANCH }} | cut -d'_' -f2)_${{ steps.buildNumber.outputs.gitBuildnumber }}"
        
        - name: Print ZEBuildNumber
          run: echo ${{ steps.ZEBuildNumber.outputs.ZEBuildNumber }}
    
